=== notJachu/hih_project/xml_files/index.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root-element (author, articles, guitarists, guitar-brands, sources)>

<!ELEMENT person (name, surrname, birth?, death?)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT surrname (#PCDATA)>
<!ELEMENT birth (#PCDATA)>
<!ELEMENT death (#PCDATA)>

<!ELEMENT author (person, index, email)>

<!ELEMENT index (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT articles (article+)>

<!ELEMENT article (headline, text)>
<!ATTLIST article id CDATA #REQUIRED>      

<!ELEMENT headline (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ATTLIST text paragraphs CDATA #REQUIRED>

<!ELEMENT guitarists (guitarist+)>

<!ELEMENT guitarist (person, description, image*, bands)>
<!ATTLIST guitarist inBand (Yes|No) "Yes">

<!ELEMENT description (#PCDATA)>

<!ELEMENT image (#PCDATA)>
<!ATTLIST image location CDATA #REQUIRED>

<!ELEMENT bands (band+)>
<!ELEMENT band (band-name, join-date)>
<!ELEMENT band-name (#PCDATA)>
<!ELEMENT join-date (#PCDATA)>

<!ELEMENT guitar-brands (brand*)>

<!ELEMENT brand (founder, country, description, models)>
<!ATTLIST brand brand-name CDATA #REQUIRED>

<!ELEMENT founder (person)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT models (#PCDATA)>

<!ELEMENT sources ((url|description)*)>

<!ELEMENT url (#PCDATA)>

=== notJachu/hih_project/xml_files/xml_with_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root-element SYSTEM "index.dtd">
<root-element>
    <author>
        <name>Jan</name>
        <surrname>StÄ…siek</surrname>
        <index>197741</index>
        <email>s197741@student.edu.gda.pl</email>
    </author>
    <articles>
        <article id="A7SY31">
            <headline>Manufacturing of the instrument</headline>
            <text paragraphs="3">Guitar manufacturers stand as the backbone of the music industry, 
                transforming raw materials into exquisite instruments that captivate musicians and audiences alike. 
                These craftsmen blend traditional techniques with modern innovations to create guitars tailored to diverse tastes and styles. 
                When it comes to electric guitars, manufacturers employ a meticulous process, ensuring every element contributes to the instrument's exceptional sound.
                Electric guitars feature pickups, small magnets wrapped with coils of wire, placed under the strings. When a guitarist plucks or strums the strings, 
                they create a magnetic field disturbance, generating a weak electrical current in the pickups. This electrical signal travels through the guitar's electronics, 
                including tone and volume controls, to an amplifier. The amplifier then magnifies the signal, producing the powerful, electrifying sound that defines the electric guitar. 
                Manufacturers constantly refine these intricate processes, 
                pushing the boundaries of creativity and engineering to provide musicians with unparalleled instruments.</text>
        </article>
        <article id="A7SY39">
            <headline>How does it all work?</headline>
            <text paragraphs="3">Understanding the anatomy of an electric guitar is essential to grasp how it produces its iconic tones. 
                The guitar's body typically consists of solid wood, allowing for better sustain and resonance. 
                The neck, usually made from hardwoods like maple or mahogany, holds the fretboard, which features metal frets divided by spaces known as semitones. 
                When a guitarist presses a string against a fret, it shortens the vibrating length of the string, producing different pitches. 
                The pickups, strategically placed near the guitar's bridge and neck, capture these vibrations and convert them into electrical signals. 
                Different pickup configurations and types offer a vast range of tones, from warm and smooth to sharp and biting. 
                Manufacturers experiment with various materials and designs, from single-coil pickups known for their bright, clear tones to humbuckers, 
                which provide a noise-resistant, powerful sound. These innovations continue to shape the electric guitar's evolution, 
                ensuring musicians have the tools they need to create groundbreaking music.</text>
        </article>
    </articles>
    <guitarists>
        <guitarist inBand="Yes">
            <name>James</name>
            <surrname>Hetfield</surrname>
            <birth>1963</birth>
            <description>Probably most famous guitarist</description>
            <image location="../resources/photo11.png"></image>
            <bands>
                <band>
                    <band-name>Metallica</band-name>
                    <join-date>1981</join-date>
                </band>
            </bands>
        </guitarist>
        <guitarist inBand="Yes">
            <name>Tony</name>
        <surrname>Iommi</surrname>
        <birth>1948</birth>
        <description>So called inventor of metal</description>
        <bands>
            <band>
                <band-name>Jethro Tull</band-name>
                <join-date>1969</join-date>
            </band>
            <band>
                <band-name>Black Sabbath</band-name>
                <join-date>1969</join-date>
            </band>
            <band>
                <band-name>Heaven and Hell</band-name>
                <join-date>2006</join-date>
            </band>
        </bands>
        </guitarist>
    </guitarists>


    <guitar-brands>
        <brand brand-name="Fender Guitars">
            <founder>
                <name>Leo</name>
                <surrname>Fender</surrname>
            </founder>
            <country>USA</country>
            <description>famous for it's strat line</description>
            <models>strat super-strat tele</models>
        </brand>
    </guitar-brands>
    <sources>
        <url>https://chat.openai.com</url>
        <url>https://wikipedia.org</url>
        <description>Articles generated by ChatGPT</description>
    </sources>
</root-element>
